### PR TITLE
added support to execute commands on mention

### PR DESCRIPTION
**Pull request by cabiste-dev**
added support to execute the commands when mentioning the bot and done some cleaning

### CODE REVIEW

**Comment by andreas-henning** [comment]
Hey @cabiste69 

This repo is a fork of [not-ilinked/Anarchy.](https://github.com/not-ilinked/Anarchy)

The upstream repo is probably where you want to place this pull request. However, let me know if you sent this my way for a reason I'm overlooking.

**Comment by andreas-henning** [comment]
Anyway @cabiste69, if you want, I'd be happy to look at this and then merge it with the upstream repo. However, if you want me to do that I'd ask you to resolve the conflicts and provide a unit test for me. Let me know.

**Comment by cabiste-dev** [comment]
> Hey @cabiste69 
> 
> This repo is a fork of [not-ilinked/Anarchy.](https://github.com/not-ilinked/Anarchy)
> 
> The upstream repo is probably where you want to place this pull request. However, let me know if you sent this my way for a reason I'm overlooking.

yes i'm aware that this is a fork and i wanted to push here because you're more active than the owner

**Comment by cabiste-dev** [comment]
> Anyway @cabiste69, if you want, I'd be happy to look at this and then merge it with the upstream repo. However, if you want me to do that I'd ask you to resolve the conflicts and provide a unit test for me. Let me know.

also i can fix the conflict but i don't know how to make a unit test :)...

**Comment by andreas-henning** [comment]
> also i can fix the conflict but i don't know how to make a unit test :)...

Creating a unit test is easy. All unit tests reside in the Anarchy.Tests project. Do this:


1. In Anarchy.Tests, create a copy of `appsettings.json` and call the copy `appsettings.Development.json`
2. In `appsettings.Development.json` set the token and channelId you want to use for testing purposes.
3. I assume the functionality you're testing is in `CommandHandler.cs`, so it probably makes sense to create the file `Commands/Command/CommandHandlerTests.cs` in the Anarchy.Tests project where you'd place the corresponding tests.
4. Create one or more unit tests which ensure your new functionality works as expected. See `MessageTests.SendMessage()` for an example.

This explains the basics:

https://learn.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2022

I don't want to add new features without an associated unit test.

**Comment by andreas-henning** [comment]
PS
Upstream repo currently can't be compiled. I'm hoping that is fixed today. Will sync master on this fork as soon as upstream is fixed.

**Comment by andreas-henning** [comment]
Let me know when you have the unit test @cabiste69

**Comment by cabiste-dev** [comment]
idk if this is enough of a test but I couldn't figure out a better way to test it @andreas-henning 
also rn the way i check for mentions it just gets the list of mentions of a message and check if the bot is the first one so 
```cs
// this will pass as a valid command
"@bot do something"

// this will pass the check for a mention but will return when looking for a command name
"hello @bot how are you"
```
if this behavior is unwanted I can change it to only work if the mention is the first word of the message

**Pull request merged**
